export const FETCHING_SIGNIN_ACCOUNT = "FETCHING_SIGNIN_ACCOUNT";
export const SUCCESS_SIGNIN_ACCOUNT = "SUCCESS_SIGNIN_ACCOUNT";
export const FAILED_SIGNIN_ACCOUNT = "FAILED_SIGNIN_ACCOUNT";
export const CLEAR_SIGNIN_ACCOUNT = "CLEAR_SIGNIN_ACCOUNT";

export const FETCHING_SIGNUP_ACCOUNT = "FETCHING_SIGNUP_ACCOUNT";
export const SUCCESS_SIGNUP_ACCOUNT = "SUCCESS_SIGNUP_ACCOUNT";
export const FAILED_SIGNUP_ACCOUNT = "FAILED_SIGNUP_ACCOUNT";
export const CLEAR_SIGNUP_ACCOUNT = "CLEAR_SIGNUP_ACCOUNT";

export const FETCHING_VERIFY_EMAIL_ACCOUNT = "FETCHING_VERIFY_EMAIL_ACCOUNT";
export const SUCCESS_VERIFY_EMAIL_ACCOUNT = "SUCCESS_VERIFY_EMAIL_ACCOUNT";
export const FAILED_VERIFY_EMAIL_ACCOUNT = "FAILED_VERIFY_EMAIL_ACCOUNT";

export const FETCHING_CHANGE_ROLE = "FETCHING_CHANGE_ROLE";
export const SUCCESS_CHANGE_ROLE = "SUCCESS_CHANGE_ROLE";
export const FAILED_CHANGE_ROLE = "FAILED_CHANGE_ROLE";

export const FETCHING_DELETE_ACCOUNT = "FETCHING_DELETE_ACCOUNT";
export const SUCCESS_DELETE_ACCOUNT = "SUCCESS_DELETE_ACCOUNT";
export const FAILED_DELETE_ACCOUNT = "FAILED_DELETE_ACCOUNT";

export const FETCHING_SIGNOUT_ACCOUNT = "FETCHING_SIGNOUT_ACCOUNT";
export const SUCCESS_SIGNOUT_ACCOUNT = "SUCCESS_SIGNOUT_ACCOUNT";
export const FAILED_SIGNOUT_ACCOUNT = "FAILED_SIGNOUT_ACCOUNT";

export const FETCHING_FORGET_PASSWORD_ACCOUNT =
  "FETCHING_FORGET_PASSWORD_ACCOUNT";
export const SUCCESS_FORGET_PASSWORD_ACCOUNT =
  "SUCCESS_FORGET_PASSWORD_ACCOUNT";
export const FAILED_FORGET_PASSWORD_ACCOUNT = "FAILED_FORGET_PASSWORD_ACCOUNT";
export const CLEAR_FORGET_PASSWORD_ACCOUNT = "CLEAR_FORGET_PASSWORD_ACCOUNT";

export const SUCCESS_JWT_EXPIRED_ACCOUNT = "SUCCESS_JWT_EXPIRED_ACCOUNT";
export const FAILED_JWT_EXPIRED_ACCOUNT = "FAILED_JWT_EXPIRED_ACCOUNT";

export const FETCHING_RESET_PASSWORD_ACCOUNT =
  "FETCHING_RESET_PASSWORD_ACCOUNT";
export const SUCCESS_RESET_PASSWORD_ACCOUNT = "SUCCESS_RESET_PASSWORD_ACCOUNT";
export const FAILED_RESET_PASSWORD_ACCOUNT = "FAILED_RESET_PASSWORD_ACCOUNT";
export const CLEAR_RESET_PASSWORD_ACCOUNT = "CLEAR_RESET_PASSWORD_ACCOUNT";

export const FETCHING_OTP_ACCOUNT = "FETCHING_OTP_ACCOUNT";
export const SUCCESS_OTP_ACCOUNT = "SUCCESS_OTP_ACCOUNT";
export const FAILED_OTP_ACCOUNT = "FAILED_OTP_ACCOUNT";

export const FETCHING_RESEND_OTP_ACCOUNT = "FETCHING_RESEND_OTP_ACCOUNT";
export const SUCCESS_RESEND_OTP_ACCOUNT = "SUCCESS_RESEND_OTP_ACCOUNT";
export const FAILED_RESEND_OTP_ACCOUNT = "FAILED_RESEND_OTP_ACCOUNT";

export const SUCCESS_EMAIL_VERIFICATION_ACCOUNT =
  "SUCCESS_EMAIL_VERIFICATION_ACCOUNT";
export const FAILED_EMAIL_VERIFICATION_ACCOUNT =
  "FAILED_EMAIL_VERIFICATION_ACCOUNT";
